configs:
  cm:
    admin.enabled: true
    create: true
    exec.enabled: true
    url: https://argo.${dns_suffix}
  params:
    server.insecure: true
  rbac:
    create: true
    policy.csv: |
      g, argo-cd:argo_admin, role:admin
    policy.default: ""
    scopes: '[groups]'
controller:
  replicas: 2
crds:
  install: true
  keep: true
fullnameOverride: argocd
redis-ha:
  enabled: false
server:
  extensions:
    enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ${cert_issuer}
    enabled: true
    hostname: argo.${dns_suffix}
    https: false
    ingressClassName: nginx
    tls: true
  replicas: 1